spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1110584913697828
            client-secret: 5e2bfccdc764d7cc9357b251d4b67287
            redirect-uri: "http://localhost:8080/login/oauth2/code/facebook"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id
server:
  port: 8080
